# Generated by Django 5.0.3 on 2024-04-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=250)),
                ('anio_egreso', models.DateTimeField()),
                ('experiencia', models.IntegerField()),
                ('experiencia_docente', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='datosusuario',
            options={'verbose_name': 'Usuarios'},
        ),
    ]
